### ISSUE TITLE
[cli] EAS Build Error

### ISSUE THREAD

**Issue by lossez** [danstepanov/create-expo-stack#30]
EAS Build error after fresh install, any solution ?
![Screenshot from 2023-10-23 05-04-40](https://github.com/danstepanov/create-expo-stack/assets/31451040/746d542d-7c2f-4c77-8cab-a4ace0b909fb)

**Comment by danstepanov** [comment]
The project does not yet support eas unless you provide the required files/configs yourself. You can do so by following [the docs](https://expo.dev/eas). We have someone working on [adding EAS](https://github.com/danstepanov/create-expo-stack/pull/29) at the moment, so I'll keep you posted as soon as that lands!

**Comment by andrew-levy** [comment]
@danstepanov I actually had this issue when running a dev build locally, and it seems to be due to corrupted asset files. When I go to open the image, I get "An error occurred while loading this image". These images are used by config plugins under the hood in development builds, which is causing this error.

The way I fixed it was by using the assets from an old non-create-expo-stack project. Is it possible the images are getting corrupted?

<img width="446" alt="Screenshot 2023-11-09 at 10 49 25 PM" src="https://github.com/danstepanov/create-expo-stack/assets/29075740/ecd6af85-8166-41a2-9901-c3c3f518314a">
