### ISSUE TITLE
[cli][FR] Check if user is set up to use RN/Expo before CLI runs

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#31]
How does Ignite do this? @frankcalise 

Do y'all have a command that installs all the RN stuff?

**Comment by frankcalise** [comment]
Ignite doesn't build from the ground up really, it's a file copy of the `boilerplate\` dir from the repo. We don't start bare and keep it that way if going the RN route or start launching create expo app if choosing Expo. It's just already made and copy that into the target directory.

In Ignite 8 (current `master` branch) we tried to get smart with having both RN/Expo flows (so user didn't have to specify at creation, but you'd eventually adopt one after spinning up the project) and trying to determine it at runtime but it didn't really work. Also was super confusing to the end user.

If that doesn't answer your question let me know and I'll try to clear it up

**Comment by danstepanov** [comment]
Not sure I follow, I'm basically wondering if a user will ever run into an issue running `npx create-expo-stack` that isn't connected to create-expo-stack (but instead iOS, Android, and/or RN setup). 

As an example, @hqasmei recently ran into this issue

![image](https://github.com/danstepanov/create-expo-stack/assets/5482800/708ce275-2e06-476f-b13c-869e33c4f2d0)

She fixed the issue by updating her iOS simulator as the issue was due to her updating Xcode but not the simulator.

Wondering whether to consider this category of issues as part of the create-expo-stack experience. I'm particularly thinking of people that start using create-expo-stack but have never used RN before. Regardless, create expo stack prioritizes expo power users so this might not be a priority.

**Comment by frankcalise** [comment]
Ah I understand now. Yeah unfortunately since Ignite/CES are "wrapping" the other experiences with sugar on top, you run into questions/issues with invalid dev envs quite often.

Most of the time you can help point people to the Environment Setup docs on RN (for example, most coming from Expo Go where everything just works, but then diving into Prebuild they don't have everything prepared). Usually it just involves educating the end user. Since your audience is a power user, when a lesser experienced user comes along they might run into some of this.

This is where the doctor type of command comes in if you check out `npx ignite-cli@next doctor`. It aggregates info about the environment so that when people do report issues you can see what tooling they're working with. Often times you can catch a wrong Java version, old globally installed package, etc.

**Comment by danstepanov** [comment]
All to say that this issue is outside of the scope of create-expo-stack
